# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.6"

dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'deb https://debian.neo4j.com stable 4.0'
        key_url: 'https://debian.neo4j.com/neotechnology.gpg.key'
    packages:
      - neo4j

services:
  - neo4j

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install .

before_script:
  - sudo sed -i 's/#dbms\.security\.auth_enabled=false/dbms.security.auth_enabled=false/' /etc/neo4j/neo4j.conf
  - sudo systemctl restart neo4j
  - sleep 10

script:
  - ./scripts/type_check.sh
  - python -m unittest discover
