# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.6"
# command to install dependencies
install: pip install tox-travis
# command to run tests
script: tox

services:
  - neo4j

addons:
  apt:
    sources:
      - sourceline: 'deb https://debian.neo4j.com stable 3.5'
        key_url: 'https://debian.neo4j.com/neotechnology.gpg.key'
    packages:
      - neo4j
