openapi: 3.0.1
info:
  title: Distance API
  version: 1.0.0
  description: An API for CRUD of the distances between samples and their nearest neighbours and
               the distances between samples and their nearest phylo tree node
servers:
  - url: http://distance-api-service/api/v1/
paths:
  /samples:
    get:
      description: Returns a list of all the samples
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Add a new sample. Duplicates are not allowed
      requestBody:
        description: Sample to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
      responses:
        201:
          description: Created. Maybe partially satisfied, the response body contains the created resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
        409:
          description: Already existed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /samples/{id}:
    get:
      description: Return a sample based on a sample ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Delete a sample based on a sample ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Deleted
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /samples/{id}/nearest-neighbours:
    get:
      description: Return the list of nearest neighbours of a sample based on a sample ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Neighbour'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Replace the list of nearest neighbours of a sample based on a sample ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: New list of nearest neighbours to replace old one.
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Neighbour'
      responses:
        200:
          description: OK. Maybe partially satisfied, the response body contains the updated resource.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Neighbour'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /samples/{id}/nearest-leaf-node:
    get:
      description: Return the nearest leaf node of a sample based on a sample ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Neighbour'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Replace the nearest leaf node of a sample based on a sample ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: New nearest leaf node to replace old one.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Neighbour'
      responses:
        200:
          description: OK. Maybe partially satisfied, the response body contains the updated resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Neighbour'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tree/{id}:
    get:
      description: Return the list of nearest samples of a tree node based on an ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Neighbour'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Sample:
      type: object
      properties:
        experiment_id:
          type: string
        nearest-neighbours:
          type: array
          items:
            $ref: '#/components/schemas/Neighbour'
        nearest-leaf-node:
          $ref: '#/components/schemas/Neighbour'
    Neighbour:
      type: object
      properties:
        id:
          type: string
        distance:
          type: integer
          format: int32
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
