openapi: 3.0.1
info:
  title: Distance API
  version: 0.0.1
servers:
- url: https://mykro.be/
- url: http://mykro.be/
paths:
  /distance:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        404:
          description: Sample not found
          content: {}
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-codegen-request-body-name: sample
components:
  schemas:
    Sample:
      type: object
      properties:
        experiment_id:
          type: string
    ApiResponse:
      type: object
      properties:
        type:
          type: string
        subType:
          type: string
        result:
          type: object
